export const GET_TODAY_ASSESSMENT_REQUEST = 'GET_TODAY_ASSESSMENT_REQUEST';
export const GET_TODAY_ASSESSMENT_SUCCESS = 'GET_TODAY_ASSESSMENT_SUCCESS';
export const GET_TODAY_ASSESSMENT_FAILURE = 'GET_TODAY_ASSESSMENT_FAILURE';
